'use strict';

/**
 * drik2026.fixture.js — Drik Panchang's full 2026 observance calendar for Jodhpur
 * (26.2389 N, 73.0243 E, +05:30), used as ground truth by verifyObservances.js.
 *
 * These are calendar FACTS (a date and the tithi it falls on), recorded here so the
 * engine can be held to them. No date in this file is ever read by the engine — the
 * engine computes from astronomy, and this file only says what the answer should be.
 *
 * `basis` records WHY the date is what it is, which is what makes a failure debuggable:
 * when a row fails, the basis says which rule to look at.
 *
 * Rows the engine is not expected to produce (civic Gregorian days like Republic Day,
 * and regional Tamil/Malayalam/Jain-calendar entries) are marked skip:true — they are
 * kept so the fixture stays a faithful record, but they are not scored.
 */

// [date DD/MM, key, basis, opts?]
const F = (date, key, basis, opts = {}) => ({ date: `${date}/2026`, key, basis, ...opts });
const SKIP = (date, key, basis) => F(date, key, basis, { skip: true });

module.exports = [
  // ── JANUARY ──
  F('01/01', 'pradosh', 'Paush Shukla Trayodashi — Guru (Thursday) Pradosh'),
  F('03/01', 'purnima-paush', 'Paush Shukla Purnima'),
  F('03/01', 'shakambhari-purnima', 'Paush Shukla Purnima'),
  F('03/01', 'anvadhan', 'day before Ishti'),
  F('04/01', 'ishti', 'day after Purnima'),
  F('06/01', 'sakat-chauth', 'Paush Krishna Chaturthi — moonrise'),
  F('06/01', 'sankashti-chaturthi', 'Paush Krishna Chaturthi — moonrise'),
  F('10/01', 'kalashtami', 'Paush Krishna Ashtami'),
  F('10/01', 'masik-krishna-janmashtami', 'Paush Krishna Ashtami'),
  F('14/01', 'sankranti-makara', 'Sun enters sidereal Capricorn'),
  F('14/01', 'pongal', 'Makar Sankranti day'),
  F('14/01', 'ekadashi-shattila', 'Paush Krishna Ekadashi'),
  F('16/01', 'pradosh', 'Paush Krishna Trayodashi — Shukra (Friday) Pradosh'),
  F('16/01', 'masik-shivaratri', 'Paush Krishna Chaturdashi'),
  F('18/01', 'mauni-amavasya', 'Paush Krishna Amavasya'),
  F('18/01', 'amavasya-paush', 'Paush Krishna Amavasya'),
  F('18/01', 'darsha-amavasya', 'Paush Krishna Amavasya'),
  F('18/01', 'anvadhan', 'day before Ishti'),
  F('19/01', 'magha-navratri', 'Magha Shukla Pratipada'),
  F('19/01', 'ishti', 'day after Amavasya'),
  F('20/01', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('22/01', 'ganesh-jayanti', 'Magha Shukla Chaturthi — madhyahna'),
  F('22/01', 'vinayaka-chaturthi', 'Magha Shukla Chaturthi'),
  F('23/01', 'vasant-panchami', 'Magha Shukla Panchami'),
  F('24/01', 'skanda-sashti', 'Magha Shukla Shashthi'),
  F('25/01', 'ratha-saptami', 'Magha Shukla Saptami'),
  F('25/01', 'bhanu-saptami', 'Saptami falling on a Sunday'),
  F('26/01', 'bhishma-ashtami', 'Magha Shukla Ashtami'),
  F('26/01', 'masik-durgashtami', 'Magha Shukla Ashtami'),
  F('29/01', 'ekadashi-jaya', 'Magha Shukla Ekadashi'),
  F('30/01', 'pradosh', 'Magha Shukla Trayodashi — Shukra (Friday) Pradosh'),

  // ── FEBRUARY ──
  F('01/02', 'purnima-magha', 'Magha Shukla Purnima'),
  F('01/02', 'anvadhan', 'day before Ishti'),
  F('02/02', 'ishti', 'day after Purnima'),
  F('05/02', 'sankashti-chaturthi', 'Magha Krishna Chaturthi — moonrise'),
  F('09/02', 'kalashtami', 'Magha Krishna Ashtami'),
  F('09/02', 'masik-krishna-janmashtami', 'Magha Krishna Ashtami'),
  F('13/02', 'sankranti-kumbha', 'Sun enters sidereal Aquarius'),
  F('13/02', 'ekadashi-vijaya', 'Magha Krishna Ekadashi'),
  F('14/02', 'pradosh', 'Magha Krishna Trayodashi — Shani (Saturday) Pradosh'),
  F('14/02', 'shani-trayodashi', 'Trayodashi falling on a Saturday'),
  F('15/02', 'maha-shivaratri', 'Magha Krishna Chaturdashi — nishita'),
  F('15/02', 'masik-shivaratri', 'Magha Krishna Chaturdashi'),
  F('17/02', 'surya-grahan', 'annular solar eclipse at Amavasya'),
  F('17/02', 'amavasya-magha', 'Magha Krishna Amavasya'),
  F('17/02', 'darsha-amavasya', 'Magha Krishna Amavasya'),
  F('17/02', 'anvadhan', 'day before Ishti'),
  F('18/02', 'ishti', 'day after Amavasya'),
  F('18/02', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('19/02', 'phulera-dooj', 'Phalguna Shukla Dwitiya'),
  F('22/02', 'skanda-sashti', 'Phalguna Shukla Shashthi'),
  F('24/02', 'masik-durgashtami', 'Phalguna Shukla Ashtami'),
  F('27/02', 'ekadashi-amalaki', 'Phalguna Shukla Ekadashi'),

  // ── MARCH ──
  F('01/03', 'pradosh', 'Phalguna Shukla Trayodashi — Ravi (Sunday) Pradosh'),
  F('02/03', 'holika-dahan', 'Phalguna Purnima — pradosh window'),
  F('03/03', 'holi', 'day after Holika Dahan'),
  F('03/03', 'purnima-phalguna', 'Phalguna Shukla Purnima'),
  F('03/03', 'chandra-grahan', 'total lunar eclipse at Purnima'),
  F('03/03', 'anvadhan', 'day before Ishti'),
  F('04/03', 'ishti', 'day after Purnima'),
  F('06/03', 'sankashti-chaturthi', 'Phalguna Krishna Chaturthi — moonrise'),
  F('08/03', 'rang-panchami', 'Phalguna Krishna Panchami'),
  F('11/03', 'shitala-ashtami', 'Phalguna Krishna Ashtami'),
  F('11/03', 'basoda', 'Phalguna Krishna Ashtami'),
  F('11/03', 'kalashtami', 'Phalguna Krishna Ashtami'),
  F('11/03', 'masik-krishna-janmashtami', 'Phalguna Krishna Ashtami'),
  F('15/03', 'sankranti-meena', 'Sun enters sidereal Pisces'),
  F('15/03', 'ekadashi-papamochani', 'Phalguna Krishna Ekadashi'),
  F('16/03', 'pradosh', 'Phalguna Krishna Trayodashi — Soma (Monday) Pradosh'),
  F('17/03', 'masik-shivaratri', 'Phalguna Krishna Chaturdashi'),
  F('18/03', 'darsha-amavasya', 'Phalguna Krishna Amavasya'),
  F('18/03', 'anvadhan', 'day before Ishti'),
  F('19/03', 'ugadi', 'Chaitra Shukla Pratipada'),
  F('19/03', 'gudi-padwa', 'Chaitra Shukla Pratipada'),
  F('19/03', 'chaitra-navratri', 'Chaitra Shukla Pratipada'),
  F('19/03', 'ishti', 'day after Amavasya'),
  F('19/03', 'amavasya-phalguna', 'Phalguna Krishna Amavasya'),
  F('20/03', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('20/03', 'vasant-sampat', 'vernal equinox'),
  F('21/03', 'gangaur', 'Chaitra Shukla Tritiya'),
  F('21/03', 'gauri-puja', 'Chaitra Shukla Tritiya'),
  F('21/03', 'matsya-jayanti', 'Chaitra Shukla Tritiya'),
  F('23/03', 'skanda-sashti', 'Chaitra Shukla Shashthi'),
  F('24/03', 'yamuna-chhath', 'Chaitra Shukla Shashthi'),
  F('26/03', 'ram-navami', 'Chaitra Shukla Navami — madhyahna (Smarta)'),
  F('26/03', 'masik-durgashtami', 'Chaitra Shukla Ashtami'),
  F('27/03', 'ram-navami-iskcon', 'Chaitra Shukla Navami (Vaishnava/ISKCON)'),
  F('27/03', 'swaminarayan-jayanti', 'Chaitra Shukla Navami'),
  F('29/03', 'ekadashi-kamada', 'Chaitra Shukla Ekadashi'),
  F('30/03', 'pradosh', 'Chaitra Shukla Trayodashi — Soma (Monday) Pradosh'),
  F('31/03', 'mahavir-jayanti', 'Chaitra Shukla Trayodashi'),

  // ── APRIL ──
  F('01/04', 'anvadhan', 'day before Ishti'),
  F('02/04', 'hanuman-jayanti', 'Chaitra Shukla Purnima'),
  F('02/04', 'purnima-chaitra', 'Chaitra Shukla Purnima'),
  F('02/04', 'ishti', 'day after Purnima'),
  F('05/04', 'sankashti-chaturthi', 'Chaitra Krishna Chaturthi — moonrise'),
  F('09/04', 'masik-krishna-janmashtami', 'Chaitra Krishna Ashtami'),
  F('10/04', 'kalashtami', 'Chaitra Krishna Ashtami'),
  F('13/04', 'ekadashi-varuthini', 'Chaitra Krishna Ekadashi'),
  F('14/04', 'sankranti-mesha', 'Sun enters sidereal Aries'),
  F('14/04', 'baisakhi', 'Mesha Sankranti day'),
  F('15/04', 'pradosh', 'Chaitra Krishna Trayodashi — Budha (Wednesday) Pradosh'),
  F('15/04', 'masik-shivaratri', 'Chaitra Krishna Chaturdashi'),
  F('17/04', 'darsha-amavasya', 'Chaitra Krishna Amavasya'),
  F('17/04', 'amavasya-chaitra', 'Chaitra Krishna Amavasya'),
  F('17/04', 'anvadhan', 'day before Ishti'),
  F('18/04', 'ishti', 'day after Amavasya'),
  F('18/04', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('19/04', 'akshaya-tritiya', 'Vaishakha Shukla Tritiya — madhyahna'),
  F('19/04', 'parashurama-jayanti', 'Vaishakha Shukla Tritiya'),
  F('21/04', 'shankaracharya-jayanti', 'Vaishakha Shukla Panchami'),
  F('22/04', 'skanda-sashti', 'Vaishakha Shukla Shashthi'),
  F('23/04', 'ganga-saptami', 'Vaishakha Shukla Saptami'),
  F('24/04', 'masik-durgashtami', 'Vaishakha Shukla Ashtami'),
  F('25/04', 'sita-navami', 'Vaishakha Shukla Navami'),
  F('27/04', 'ekadashi-mohini', 'Vaishakha Shukla Ekadashi'),
  F('28/04', 'pradosh', 'Vaishakha Shukla Trayodashi — Bhauma (Tuesday) Pradosh'),
  F('30/04', 'narasimha-jayanti', 'Vaishakha Shukla Chaturdashi'),

  // ── MAY ──
  F('01/05', 'buddha-purnima', 'Vaishakha Shukla Purnima'),
  F('01/05', 'purnima-vaishakha', 'Vaishakha Shukla Purnima'),
  F('01/05', 'kurma-jayanti', 'Vaishakha Shukla Purnima'),
  F('01/05', 'anvadhan', 'day before Ishti'),
  F('02/05', 'narada-jayanti', 'Vaishakha Krishna Pratipada'),
  F('02/05', 'ishti', 'day after Purnima'),
  F('05/05', 'sankashti-chaturthi', 'Vaishakha Krishna Chaturthi — moonrise'),
  F('09/05', 'kalashtami', 'Vaishakha Krishna Ashtami'),
  F('09/05', 'masik-krishna-janmashtami', 'Vaishakha Krishna Ashtami'),
  F('13/05', 'ekadashi-apara', 'Vaishakha Krishna Ekadashi'),
  F('14/05', 'pradosh', 'Vaishakha Krishna Trayodashi — Guru (Thursday) Pradosh'),
  F('15/05', 'sankranti-vrishabha', 'Sun enters sidereal Taurus'),
  F('15/05', 'masik-shivaratri', 'Vaishakha Krishna Chaturdashi'),
  F('16/05', 'vat-savitri', 'Vaishakha Krishna Amavasya'),
  F('16/05', 'shani-jayanti', 'Vaishakha Krishna Amavasya'),
  F('16/05', 'darsha-amavasya', 'Vaishakha Krishna Amavasya'),
  F('16/05', 'amavasya-vaishakha', 'Vaishakha Krishna Amavasya'),
  F('16/05', 'anvadhan', 'day before Ishti'),
  F('17/05', 'adhika-masa-start', 'Jyeshtha Adhika begins — month with no sankranti'),
  F('17/05', 'ishti', 'day after Amavasya'),
  F('17/05', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('21/05', 'skanda-sashti', 'Jyeshtha Adhika Shukla Shashthi'),
  F('23/05', 'masik-durgashtami', 'Jyeshtha Adhika Shukla Ashtami'),
  F('25/05', 'ganga-dussehra', 'Jyeshtha Shukla Dashami'),
  F('27/05', 'ekadashi-padmini', 'Jyeshtha Adhika Shukla Ekadashi — only in an adhika month'),
  F('28/05', 'pradosh', 'Jyeshtha Adhika Shukla Trayodashi — Guru (Thursday) Pradosh'),
  F('31/05', 'purnima-jyeshtha-adhika', 'Jyeshtha Adhika Shukla Purnima'),
  F('31/05', 'anvadhan', 'day before Ishti'),

  // ── JUNE ──
  F('01/06', 'ishti', 'day after Purnima'),
  F('03/06', 'sankashti-chaturthi', 'Jyeshtha Adhika Krishna Chaturthi — moonrise'),
  F('07/06', 'bhanu-saptami', 'Saptami falling on a Sunday'),
  F('08/06', 'kalashtami', 'Jyeshtha Adhika Krishna Ashtami'),
  F('08/06', 'masik-krishna-janmashtami', 'Jyeshtha Adhika Krishna Ashtami'),
  F('11/06', 'ekadashi-parama', 'Jyeshtha Adhika Krishna Ekadashi — only in an adhika month'),
  F('12/06', 'pradosh', 'Jyeshtha Adhika Krishna Trayodashi — Shukra (Friday) Pradosh'),
  F('13/06', 'masik-shivaratri', 'Jyeshtha Adhika Krishna Chaturdashi'),
  F('14/06', 'darsha-amavasya', 'Jyeshtha Adhika Krishna Amavasya'),
  F('14/06', 'anvadhan', 'day before Ishti'),
  F('15/06', 'adhika-masa-end', 'Jyeshtha Adhika ends'),
  F('15/06', 'sankranti-mithuna', 'Sun enters sidereal Gemini'),
  F('15/06', 'amavasya-jyeshtha-adhika', 'Jyeshtha Adhika Krishna Amavasya'),
  F('15/06', 'ishti', 'day after Amavasya'),
  F('16/06', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('19/06', 'skanda-sashti', 'Jyeshtha Shukla Shashthi'),
  F('21/06', 'bhanu-saptami', 'Saptami falling on a Sunday'),
  F('21/06', 'summer-solstice', 'longest day'),
  F('22/06', 'masik-durgashtami', 'Jyeshtha Shukla Ashtami'),
  F('23/06', 'mahesh-navami', 'Jyeshtha Shukla Navami'),
  F('25/06', 'ekadashi-nirjala', 'Jyeshtha Shukla Ekadashi'),
  F('25/06', 'gayatri-jayanti', 'Jyeshtha Shukla Ekadashi'),
  F('27/06', 'pradosh', 'Jyeshtha Shukla Trayodashi — Shani (Saturday) Pradosh'),
  F('27/06', 'shani-trayodashi', 'Trayodashi falling on a Saturday'),
  F('29/06', 'vat-purnima', 'Jyeshtha Shukla Purnima'),
  F('29/06', 'purnima-jyeshtha', 'Jyeshtha Shukla Purnima'),
  F('29/06', 'anvadhan', 'day before Ishti'),
  F('30/06', 'ishti', 'day after Purnima'),

  // ── JULY ──
  F('03/07', 'sankashti-chaturthi', 'Jyeshtha Krishna Chaturthi — moonrise'),
  F('07/07', 'kalashtami', 'Jyeshtha Krishna Ashtami'),
  F('07/07', 'masik-krishna-janmashtami', 'Jyeshtha Krishna Ashtami'),
  F('10/07', 'ekadashi-yogini', 'Jyeshtha Krishna Ekadashi'),
  F('11/07', 'ekadashi-yogini-gauna', 'Vaishnava Ekadashi — the day after, when the tithi spans two sunrises'),
  F('12/07', 'pradosh', 'Jyeshtha Krishna Trayodashi — Ravi (Sunday) Pradosh'),
  F('12/07', 'masik-shivaratri', 'Jyeshtha Krishna Chaturdashi'),
  F('14/07', 'darsha-amavasya', 'Jyeshtha Krishna Amavasya'),
  F('14/07', 'amavasya-jyeshtha', 'Jyeshtha Krishna Amavasya'),
  F('14/07', 'anvadhan', 'day before Ishti'),
  F('15/07', 'ashadha-navratri', 'Ashadha Shukla Pratipada'),
  F('15/07', 'ishti', 'day after Amavasya'),
  F('15/07', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('16/07', 'jagannath-rathyatra', 'Ashadha Shukla Dwitiya'),
  F('16/07', 'sankranti-karka', 'Sun enters sidereal Cancer'),
  F('17/07', 'vinayaka-chaturthi', 'Ashadha Shukla Chaturthi'),
  F('19/07', 'skanda-sashti', 'Ashadha Shukla Shashthi'),
  F('21/07', 'parvati-jayanti', 'Ashadha Shukla Ashtami'),
  F('21/07', 'masik-durgashtami', 'Ashadha Shukla Ashtami'),
  F('22/07', 'bhadali-navami', 'Ashadha Shukla Navami'),
  F('24/07', 'asha-dashami', 'Ashadha Shukla Dashami'),
  F('25/07', 'ekadashi-devshayani', 'Ashadha Shukla Ekadashi'),
  F('25/07', 'gauri-vrat-start', 'Ashadha Shukla Dwadashi'),
  F('26/07', 'pradosh', 'Ashadha Shukla Trayodashi — Ravi (Sunday) Pradosh'),
  F('29/07', 'guru-purnima', 'Ashadha Shukla Purnima'),
  F('29/07', 'purnima-ashadha', 'Ashadha Shukla Purnima'),
  F('29/07', 'anvadhan', 'day before Ishti'),
  F('30/07', 'ishti', 'day after Purnima'),

  // ── AUGUST ──
  F('02/08', 'sankashti-chaturthi', 'Ashadha Krishna Chaturthi — moonrise'),
  F('05/08', 'kalashtami', 'Ashadha Krishna Ashtami'),
  F('05/08', 'masik-krishna-janmashtami', 'Ashadha Krishna Ashtami'),
  F('09/08', 'ekadashi-kamika', 'Ashadha Krishna Ekadashi'),
  F('10/08', 'pradosh', 'Ashadha Krishna Trayodashi — Soma (Monday) Pradosh'),
  F('11/08', 'masik-shivaratri', 'Ashadha Krishna Chaturdashi'),
  F('12/08', 'hariyali-amavasya', 'Shravana (purnimanta) Krishna Amavasya'),
  F('12/08', 'surya-grahan', 'total solar eclipse at Amavasya'),
  F('12/08', 'darsha-amavasya', 'Ashadha Krishna Amavasya'),
  F('12/08', 'amavasya-ashadha', 'Ashadha Krishna Amavasya'),
  F('12/08', 'anvadhan', 'day before Ishti'),
  F('13/08', 'ishti', 'day after Amavasya'),
  F('14/08', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('15/08', 'hariyali-teej', 'Shravana Shukla Tritiya'),
  F('17/08', 'nag-panchami', 'Shravana Shukla Panchami'),
  F('17/08', 'sankranti-simha', 'Sun enters sidereal Leo'),
  F('17/08', 'skanda-sashti', 'Shravana Shukla Shashthi'),
  F('17/08', 'shravana-somvar-1', 'first Monday of Shravana'),
  F('18/08', 'mangala-gauri-1', 'first Tuesday of Shravana'),
  F('20/08', 'masik-durgashtami', 'Shravana Shukla Ashtami'),
  F('23/08', 'ekadashi-putrada-shravana', 'Shravana Shukla Ekadashi'),
  F('24/08', 'shravana-somvar-2', 'second Monday of Shravana'),
  F('25/08', 'pradosh', 'Shravana Shukla Trayodashi — Bhauma (Tuesday) Pradosh'),
  F('26/08', 'onam', 'Sun in Leo and Shravana nakshatra'),
  F('28/08', 'raksha-bandhan', 'Shravana Shukla Purnima'),
  F('28/08', 'purnima-shravana', 'Shravana Shukla Purnima'),
  F('28/08', 'chandra-grahan', 'partial lunar eclipse at Purnima'),
  F('28/08', 'varalakshmi-vrat', 'Friday before Shravana Purnima'),
  F('28/08', 'ishti', 'day after Purnima'),
  F('27/08', 'anvadhan', 'day before Ishti'),
  F('31/08', 'kajri-teej', 'Shravana Krishna Tritiya'),
  F('31/08', 'sankashti-chaturthi', 'Shravana Krishna Chaturthi — moonrise'),
  F('31/08', 'shravana-somvar-3', 'third Monday of Shravana'),

  // ── SEPTEMBER ──
  F('01/09', 'mangala-gauri-3', 'third Tuesday of Shravana'),
  F('04/09', 'krishna-janmashtami', 'Shravana Krishna Ashtami — nishita'),
  F('04/09', 'kalashtami', 'Shravana Krishna Ashtami'),
  F('04/09', 'masik-krishna-janmashtami', 'Shravana Krishna Ashtami'),
  F('05/09', 'dahi-handi', 'day after Janmashtami'),
  F('07/09', 'ekadashi-aja', 'Shravana Krishna Ekadashi'),
  F('07/09', 'shravana-somvar-4', 'fourth Monday of Shravana'),
  F('08/09', 'pradosh', 'Shravana Krishna Trayodashi — Bhauma (Tuesday) Pradosh'),
  F('09/09', 'masik-shivaratri', 'Shravana Krishna Chaturdashi'),
  F('10/09', 'darsha-amavasya', 'Shravana Krishna Amavasya'),
  F('10/09', 'anvadhan', 'day before Ishti'),
  F('11/09', 'amavasya-shravana', 'Shravana Krishna Amavasya'),
  F('11/09', 'ishti', 'day after Amavasya'),
  F('13/09', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('14/09', 'hartalika-teej', 'Bhadrapada Shukla Tritiya'),
  F('14/09', 'ganesh-chaturthi', 'Bhadrapada Shukla Chaturthi — madhyahna'),
  F('15/09', 'rishi-panchami', 'Bhadrapada Shukla Panchami'),
  F('16/09', 'balaram-jayanti', 'Bhadrapada Shukla Shashthi'),
  F('16/09', 'skanda-sashti', 'Bhadrapada Shukla Shashthi'),
  F('17/09', 'sankranti-kanya', 'Sun enters sidereal Virgo'),
  F('17/09', 'vishwakarma-puja', 'Kanya Sankranti day'),
  F('19/09', 'radha-ashtami', 'Bhadrapada Shukla Ashtami'),
  F('19/09', 'masik-durgashtami', 'Bhadrapada Shukla Ashtami'),
  F('22/09', 'ekadashi-parivartini', 'Bhadrapada Shukla Ekadashi'),
  F('23/09', 'vamana-jayanti', 'Bhadrapada Shukla Dwadashi'),
  F('23/09', 'sharad-sampat', 'autumnal equinox'),
  F('24/09', 'pradosh', 'Bhadrapada Shukla Trayodashi — Guru (Thursday) Pradosh'),
  F('25/09', 'anant-chaturdashi', 'Bhadrapada Shukla Chaturdashi'),
  F('25/09', 'ganesh-visarjan', 'Bhadrapada Shukla Chaturdashi'),
  F('26/09', 'purnima-bhadrapada', 'Bhadrapada Shukla Purnima'),
  F('26/09', 'anvadhan', 'day before Ishti'),
  F('27/09', 'pitrupaksha-start', 'Bhadrapada Krishna Pratipada'),
  F('27/09', 'ishti', 'day after Purnima'),
  F('29/09', 'sankashti-chaturthi', 'Bhadrapada Krishna Chaturthi — moonrise'),

  // ── OCTOBER ──
  F('03/10', 'kalashtami', 'Bhadrapada Krishna Ashtami'),
  F('03/10', 'masik-krishna-janmashtami', 'Bhadrapada Krishna Ashtami'),
  F('03/10', 'jivitputrika-vrat', 'Bhadrapada Krishna Ashtami'),
  F('06/10', 'ekadashi-indira', 'Bhadrapada Krishna Ekadashi'),
  F('08/10', 'pradosh', 'Bhadrapada Krishna Trayodashi — Guru (Thursday) Pradosh'),
  F('08/10', 'masik-shivaratri', 'Bhadrapada Krishna Chaturdashi'),
  F('10/10', 'sarvapitri-amavasya', 'Bhadrapada Krishna Amavasya'),
  F('10/10', 'darsha-amavasya', 'Bhadrapada Krishna Amavasya'),
  F('10/10', 'amavasya-bhadrapada', 'Bhadrapada Krishna Amavasya'),
  F('10/10', 'anvadhan', 'day before Ishti'),
  F('11/10', 'navratri-start', 'Ashwina Shukla Pratipada'),
  F('11/10', 'ghatasthapana', 'Ashwina Shukla Pratipada'),
  F('11/10', 'ishti', 'day after Amavasya'),
  F('12/10', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('16/10', 'saraswati-avahan', 'Ashwina, Moola nakshatra'),
  F('16/10', 'skanda-sashti', 'Ashwina Shukla Shashthi'),
  F('17/10', 'saraswati-puja', 'Ashwina, Purvashadha nakshatra'),
  F('17/10', 'sankranti-tula', 'Sun enters sidereal Libra'),
  F('19/10', 'durga-ashtami', 'Ashwina Shukla Ashtami'),
  F('19/10', 'maha-navami', 'Ashwina Shukla Navami — aparahna'),
  F('19/10', 'masik-durgashtami', 'Ashwina Shukla Ashtami'),
  F('20/10', 'vijayadashami', 'Ashwina Shukla Dashami — aparahna'),
  F('20/10', 'ayudha-puja', 'Ashwina Shukla Navami'),
  F('22/10', 'ekadashi-papankusha', 'Ashwina Shukla Ekadashi'),
  F('23/10', 'pradosh', 'Ashwina Shukla Trayodashi — Shukra (Friday) Pradosh'),
  F('25/10', 'sharad-purnima', 'Ashwina Shukla Purnima — nishita'),
  F('25/10', 'kojagara-puja', 'Ashwina Shukla Purnima'),
  F('25/10', 'anvadhan', 'day before Ishti'),
  F('26/10', 'purnima-ashwina', 'Ashwina Shukla Purnima'),
  F('26/10', 'valmiki-jayanti', 'Ashwina Shukla Purnima'),
  F('26/10', 'ishti', 'day after Purnima'),
  F('29/10', 'karwa-chauth', 'Ashwina Krishna Chaturthi — moonrise'),
  F('29/10', 'sankashti-chaturthi', 'Ashwina Krishna Chaturthi — moonrise'),

  // ── NOVEMBER ──
  F('01/11', 'ahoi-ashtami', 'Ashwina Krishna Ashtami — pradosh'),
  F('01/11', 'kalashtami', 'Ashwina Krishna Ashtami'),
  F('01/11', 'masik-krishna-janmashtami', 'Ashwina Krishna Ashtami'),
  F('01/11', 'bhanu-saptami', 'Saptami falling on a Sunday'),
  F('05/11', 'ekadashi-rama', 'Ashwina Krishna Ekadashi'),
  F('05/11', 'govatsa-dwadashi', 'Ashwina Krishna Dwadashi'),
  F('06/11', 'dhanteras', 'Ashwina Krishna Trayodashi — pradosh'),
  F('06/11', 'pradosh', 'Ashwina Krishna Trayodashi — Shukra (Friday) Pradosh'),
  F('07/11', 'kali-chaudas', 'Ashwina Krishna Chaturdashi'),
  F('07/11', 'masik-shivaratri', 'Ashwina Krishna Chaturdashi'),
  F('08/11', 'diwali', 'Ashwina/Kartika Krishna Amavasya — pradosh'),
  F('08/11', 'naraka-chaturdashi', 'Ashwina Krishna Chaturdashi'),
  F('08/11', 'darsha-amavasya', 'Ashwina Krishna Amavasya'),
  F('09/11', 'govardhan-puja', 'Kartika Shukla Pratipada'),
  F('09/11', 'amavasya-ashwina', 'Ashwina Krishna Amavasya'),
  F('09/11', 'anvadhan', 'day before Ishti'),
  F('10/11', 'gujarati-new-year', 'Kartika Shukla Pratipada'),
  F('10/11', 'ishti', 'day after Amavasya'),
  F('11/11', 'bhai-dooj', 'Kartika Shukla Dwitiya — aparahna'),
  F('11/11', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('13/11', 'labh-chaturthi', 'Kartika Shukla Chaturthi'),
  F('15/11', 'chhath-puja', 'Kartika Shukla Shashthi'),
  F('15/11', 'skanda-sashti', 'Kartika Shukla Shashthi'),
  F('16/11', 'sankranti-vrishchika', 'Sun enters sidereal Scorpio'),
  F('17/11', 'gopashtami', 'Kartika Shukla Ashtami'),
  F('17/11', 'masik-durgashtami', 'Kartika Shukla Ashtami'),
  F('18/11', 'akshaya-navami', 'Kartika Shukla Navami'),
  F('20/11', 'ekadashi-devutthana', 'Kartika Shukla Ekadashi'),
  F('21/11', 'tulsi-vivah', 'Kartika Shukla Dwadashi'),
  F('21/11', 'ekadashi-devutthana-gauna', 'Vaishnava Ekadashi — the day after'),
  F('22/11', 'pradosh', 'Kartika Shukla Trayodashi — Ravi (Sunday) Pradosh'),
  F('23/11', 'vaikuntha-chaturdashi', 'Kartika Shukla Chaturdashi'),
  F('24/11', 'kartik-purnima', 'Kartika Shukla Purnima'),
  F('24/11', 'purnima-kartika', 'Kartika Shukla Purnima'),
  F('24/11', 'dev-diwali', 'Kartika Shukla Purnima'),
  F('24/11', 'guru-nanak-jayanti', 'Kartika Shukla Purnima'),
  F('24/11', 'anvadhan', 'day before Ishti'),
  F('25/11', 'ishti', 'day after Purnima'),
  F('27/11', 'sankashti-chaturthi', 'Kartika Krishna Chaturthi — moonrise'),
  F('30/11', 'masik-krishna-janmashtami', 'Kartika Krishna Ashtami'),

  // ── DECEMBER ──
  F('01/12', 'kalabhairav-jayanti', 'Kartika Krishna Ashtami'),
  F('01/12', 'kalashtami', 'Kartika Krishna Ashtami'),
  F('04/12', 'ekadashi-utpanna', 'Kartika Krishna Ekadashi'),
  F('06/12', 'pradosh', 'Kartika Krishna Trayodashi — Ravi (Sunday) Pradosh'),
  F('07/12', 'masik-shivaratri', 'Kartika Krishna Chaturdashi'),
  F('08/12', 'darsha-amavasya', 'Kartika Krishna Amavasya'),
  F('08/12', 'amavasya-kartika', 'Kartika Krishna Amavasya'),
  F('08/12', 'anvadhan', 'day before Ishti'),
  F('09/12', 'ishti', 'day after Amavasya'),
  F('10/12', 'chandra-darshana', 'first moon sighting after Amavasya'),
  F('14/12', 'vivah-panchami', 'Margashirsha Shukla Panchami'),
  F('15/12', 'skanda-sashti', 'Margashirsha Shukla Shashthi'),
  F('15/12', 'champa-sashti', 'Margashirsha Shukla Shashthi'),
  F('16/12', 'sankranti-dhanu', 'Sun enters sidereal Sagittarius'),
  F('17/12', 'masik-durgashtami', 'Margashirsha Shukla Ashtami'),
  F('20/12', 'gita-jayanti', 'Margashirsha Shukla Ekadashi'),
  F('20/12', 'ekadashi-mokshada', 'Margashirsha Shukla Ekadashi'),
  F('21/12', 'pradosh', 'Margashirsha Shukla Trayodashi — Soma (Monday) Pradosh'),
  F('22/12', 'winter-solstice', 'shortest day'),
  F('23/12', 'datta-jayanti', 'Margashirsha Shukla Purnima'),
  F('23/12', 'purnima-margashirsha', 'Margashirsha Shukla Purnima'),
  F('23/12', 'annapurna-jayanti', 'Margashirsha Shukla Purnima'),
  F('23/12', 'anvadhan', 'day before Ishti'),
  F('24/12', 'ishti', 'day after Purnima'),
  F('26/12', 'sankashti-chaturthi', 'Margashirsha Krishna Chaturthi — moonrise'),
  F('30/12', 'kalashtami', 'Margashirsha Krishna Ashtami'),
  F('30/12', 'masik-krishna-janmashtami', 'Margashirsha Krishna Ashtami'),

  // Regional/sectarian calendars the engine does not model (kept for the record, not scored).
  SKIP('01/01', 'rohini-vrat', 'Jain calendar'),
  SKIP('13/01', 'lohri', 'day before Makar Sankranti — Punjabi'),
  SKIP('27/01', 'masik-kartigai', 'Krittika nakshatra — Tamil solar'),
  SKIP('03/08', 'aadi-perukku', 'Tamil Aadi 18th day'),
];
