export type LegalSec = { h: { en: string; hi: string }; b: { en: string; hi: string } }

const UPDATED = { en: 'Last updated: 16 July 2026', hi: 'अंतिम अपडेट: 16 जुलाई 2026' };
const CONTACT_EMAIL = 'support@shreeyantra.app';

interface Sec { h: { en: string; hi: string }; b: { en: string; hi: string } }

const PRIVACY: Sec[] = [
  {
    h: { en: '1. What this policy covers', hi: '1. यह नीति किस बारे में है' },
    b: {
      en: 'Shree Yantra ("the app", "we") is a Vedic astrology and spiritual companion app. This policy explains what information we collect when you use the app, why we collect it, who it is shared with, and the choices you have. By creating an account you agree to this policy.',
      hi: 'श्री यंत्र ("ऐप", "हम") एक वैदिक ज्योतिष व आध्यात्मिक साथी ऐप है। यह नीति बताती है कि ऐप के उपयोग के दौरान हम कौन-सी जानकारी लेते हैं, क्यों लेते हैं, किसके साथ साझा होती है, और आपके पास कौन-से विकल्प हैं। खाता बनाकर आप इस नीति से सहमत होते हैं।',
    },
  },
  {
    h: { en: '2. Information you give us', hi: '2. जो जानकारी आप हमें देते हैं' },
    b: {
      en: '• Account: your mobile number (verified by OTP) or your Google account\'s name, email and profile photo if you sign in with Google.\n• Birth details: name, date of birth, time of birth and birth place — these are required to compute your kundli, dasha, predictions and match-making. They are the heart of the service.\n• Questions you ask: when you use the "Ask" / guidance features, your questions and the responses are stored with your account so your history stays available to you.\n• Practice data: jaap (mantra) counts, saved items, reading progress and puja-samagri checklists are saved to your account so they survive a phone change.',
      hi: '• खाता: आपका मोबाइल नंबर (OTP से सत्यापित), या Google से साइन-इन करने पर आपके Google खाते का नाम, ईमेल व प्रोफ़ाइल फोटो।\n• जन्म विवरण: नाम, जन्म-तिथि, जन्म-समय व जन्म-स्थान — ये कुंडली, दशा, भविष्यवाणियों व कुंडली मिलान की गणना के लिए आवश्यक हैं। यही सेवा का आधार है।\n• आपके प्रश्न: "पूछें"/मार्गदर्शन सुविधाओं में पूछे गए प्रश्न व उनके उत्तर आपके खाते में सहेजे जाते हैं, ताकि आपका इतिहास आपको मिलता रहे।\n• साधना डेटा: जाप गणना, सहेजी सामग्री, पठन प्रगति व पूजा-सामग्री सूचियाँ आपके खाते में सुरक्षित रहती हैं, ताकि फ़ोन बदलने पर भी बनी रहें।',
    },
  },
  {
    h: { en: '3. Information collected automatically', hi: '3. स्वतः एकत्र होने वाली जानकारी' },
    b: {
      en: '• Location: with your permission, the app reads your device\'s approximate location to show the panchang, choghadiya and muhurat for where you actually are. You can deny this permission — the app then falls back to your profile city. Location is read when you use these features; the app does not track you in the background.\n• Usage & device data: screens you visit, features you use, device model, OS version, app version and your IP address (from which an approximate city is derived) — used to fix problems and improve the app.\n• Notifications: a push-notification token, so we can deliver reminders and updates you have enabled.',
      hi: '• लोकेशन: आपकी अनुमति से ऐप आपके डिवाइस की अनुमानित लोकेशन पढ़ता है, ताकि पंचांग, चौघड़िया व मुहूर्त आपकी वर्तमान जगह के अनुसार दिखें। अनुमति न देने पर ऐप आपकी प्रोफ़ाइल के शहर का उपयोग करता है। लोकेशन इन्हीं सुविधाओं के उपयोग के समय पढ़ी जाती है; ऐप बैकग्राउंड में आपको ट्रैक नहीं करता।\n• उपयोग व डिवाइस डेटा: कौन-सी स्क्रीन/सुविधाएँ उपयोग हुईं, डिवाइस मॉडल, OS संस्करण, ऐप संस्करण व IP पता (जिससे अनुमानित शहर निकलता है) — समस्याएँ सुधारने व ऐप बेहतर बनाने हेतु।\n• सूचनाएँ: पुश-नोटिफ़िकेशन टोकन, ताकि आपके चालू किए रिमाइंडर व अपडेट पहुँच सकें।',
    },
  },
  {
    h: { en: '4. How readings are generated', hi: '4. रीडिंग कैसे बनती हैं' },
    b: {
      en: 'Astrological positions (planets, tithi, nakshatra, muhurat) are computed deterministically from astronomical data. The written explanations, predictions and answers are generated by automated computer systems: to produce them, the relevant inputs (such as your birth details or your question) are processed by trusted third-party cloud services under agreements that restrict them from using your data for anything else. Generated guidance is informational — see the Terms for the full disclaimer.',
      hi: 'ग्रह-स्थिति, तिथि, नक्षत्र व मुहूर्त की गणना खगोलीय डेटा से नियतात्मक (deterministic) रूप से होती है। लिखित व्याख्याएँ, भविष्यवाणियाँ व उत्तर स्वचालित कंप्यूटर प्रणालियों से बनते हैं: इसके लिए आवश्यक इनपुट (जैसे जन्म विवरण या आपका प्रश्न) विश्वसनीय थर्ड-पार्टी क्लाउड सेवाओं को संसाधित करने हेतु भेजे जाते हैं, ऐसे अनुबंधों के अंतर्गत जो उन्हें आपके डेटा का अन्य उपयोग करने से रोकते हैं। यह मार्गदर्शन सूचनात्मक है — पूर्ण अस्वीकरण हेतु सेवा-शर्तें देखें।',
    },
  },
  {
    h: { en: '5. Who we share data with', hi: '5. डेटा किसके साथ साझा होता है' },
    b: {
      en: 'We never sell your personal data. It is shared only with the service providers needed to run the app: Google (sign-in and push notifications), astrology-computation and content-generation cloud services (only the inputs needed for your reading), map/geocoding services (a place name, to find its coordinates), and payment providers when you buy a subscription (we do not store your card or UPI credentials). Each provider may process data only to provide its service to us. We may disclose information if the law requires it.',
      hi: 'हम आपका व्यक्तिगत डेटा कभी नहीं बेचते। यह केवल उन्हीं सेवा-प्रदाताओं से साझा होता है जो ऐप चलाने हेतु आवश्यक हैं: Google (साइन-इन व पुश सूचनाएँ), ज्योतिष-गणना व सामग्री-निर्माण क्लाउड सेवाएँ (केवल रीडिंग हेतु आवश्यक इनपुट), नक्शा/जियोकोडिंग सेवाएँ (स्थान का नाम, उसके निर्देशांक जानने हेतु), और सदस्यता खरीदने पर भुगतान-प्रदाता (हम आपका कार्ड/UPI विवरण संग्रहीत नहीं करते)। हर प्रदाता डेटा केवल हमें सेवा देने हेतु ही संसाधित कर सकता है। कानून की अपेक्षा होने पर जानकारी प्रकट की जा सकती है।',
    },
  },
  {
    h: { en: '6. Security', hi: '6. सुरक्षा' },
    b: {
      en: 'Your sign-in credentials are stored in your device\'s hardware-backed secure keystore, data travels over encrypted connections, and your account is protected by single-device login — signing in on a new device automatically signs out the old one. No system is 100% secure, but we follow industry practice (OWASP mobile-security guidance) and keep tightening it.',
      hi: 'आपकी साइन-इन क्रेडेंशियल डिवाइस के हार्डवेयर-समर्थित सुरक्षित कीस्टोर में रहती हैं, डेटा एन्क्रिप्टेड कनेक्शन से जाता है, और खाता सिंगल-डिवाइस लॉगिन से सुरक्षित है — नए डिवाइस पर साइन-इन करते ही पुराना अपने-आप लॉगआउट हो जाता है। कोई प्रणाली 100% सुरक्षित नहीं होती, पर हम उद्योग-मानक (OWASP मोबाइल-सुरक्षा दिशानिर्देश) अपनाते हैं और उसे लगातार कसते रहते हैं।',
    },
  },
  {
    h: { en: '7. Retention & deletion', hi: '7. डेटा कब तक रहता है, कैसे हटेगा' },
    b: {
      en: 'Your data is kept while your account is active. You can request a copy of your data, correction of inaccurate details, or permanent deletion of your account and data by contacting us (Section 9) — deletion is completed within 30 days except records we must keep under law (e.g. payment/tax records). Uninstalling the app removes on-device data such as your cached readings; your account remains until you ask us to delete it.',
      hi: 'आपका डेटा तब तक रहता है जब तक खाता सक्रिय है। आप हमसे संपर्क कर (धारा 9) अपने डेटा की प्रति, गलत विवरण का सुधार, या खाते व डेटा को स्थायी रूप से हटाने का अनुरोध कर सकते हैं — हटाने की प्रक्रिया 30 दिनों में पूर्ण होती है, सिवाय उन अभिलेखों के जिन्हें कानूनन रखना आवश्यक है (जैसे भुगतान/कर अभिलेख)। ऐप अनइंस्टॉल करने से डिवाइस पर सहेजा डेटा हट जाता है; खाता तब तक रहता है जब तक आप हटाने को न कहें।',
    },
  },
  {
    h: { en: '8. Your rights & children', hi: '8. आपके अधिकार व बच्चों की सुरक्षा' },
    b: {
      en: 'Under India\'s Digital Personal Data Protection Act, 2023 you have the right to access, correct and erase your personal data, to withdraw consent (via the in-app privacy toggles, device permissions, or by contacting us), and to grievance redressal. The app is intended for users aged 18 and above; users below 18 may use it only with a parent\'s or guardian\'s consent, and we do not knowingly collect children\'s data for advertising or tracking.',
      hi: 'भारत के डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम, 2023 के अंतर्गत आपको अपने डेटा तक पहुँच, सुधार व मिटाने का, सहमति वापस लेने का (ऐप की गोपनीयता टॉगल, डिवाइस अनुमतियों, या हमसे संपर्क द्वारा), और शिकायत-निवारण का अधिकार है। ऐप 18 वर्ष व अधिक आयु के लिए है; 18 से कम आयु के उपयोगकर्ता केवल माता-पिता/अभिभावक की सहमति से ही इसका उपयोग करें — हम जानबूझकर बच्चों का डेटा विज्ञापन या ट्रैकिंग हेतु एकत्र नहीं करते।',
    },
  },
  {
    h: { en: '9. Contact & grievance officer', hi: '9. संपर्क व शिकायत अधिकारी' },
    b: {
      en: `For any privacy question, data request or complaint, write to ${CONTACT_EMAIL} (or use Help & Support in the app). As required by Indian IT rules, grievances are acknowledged within 48 hours and resolved within 30 days. If this policy changes materially, we will notify you in the app before the change takes effect.`,
      hi: `किसी भी गोपनीयता प्रश्न, डेटा अनुरोध या शिकायत हेतु ${CONTACT_EMAIL} पर लिखें (या ऐप में सहायता व समर्थन का उपयोग करें)। भारतीय IT नियमों के अनुसार शिकायत की पावती 48 घंटे में व समाधान 30 दिनों में किया जाता है। नीति में कोई महत्वपूर्ण बदलाव होने पर लागू होने से पहले ऐप में सूचित किया जाएगा।`,
    },
  },
];

const TERMS: Sec[] = [
  {
    h: { en: '1. Acceptance of these terms', hi: '1. शर्तों की स्वीकृति' },
    b: {
      en: 'These Terms of Service are an agreement between you and Shree Yantra for the use of this app and its services. By creating an account or using the app you accept these terms and the Privacy Policy. If you do not agree, please do not use the app.',
      hi: 'ये सेवा-शर्तें आपके और श्री यंत्र के बीच इस ऐप व इसकी सेवाओं के उपयोग का अनुबंध हैं। खाता बनाकर या ऐप का उपयोग कर आप इन शर्तों व गोपनीयता नीति को स्वीकार करते हैं। सहमत न हों तो कृपया ऐप का उपयोग न करें।',
    },
  },
  {
    h: { en: '2. What the app provides', hi: '2. ऐप क्या प्रदान करता है' },
    b: {
      en: 'Shree Yantra provides Vedic-astrology tools (kundli, dasha, predictions, kundli milan), the daily panchang, choghadiya and muhurat timings, vrat-festival calendars, remedies and guidance features, and a Divine Library of scriptures (Vedas, Puranas, Gita, Ramayana and more) with audio. Some features require a paid subscription.',
      hi: 'श्री यंत्र वैदिक-ज्योतिष उपकरण (कुंडली, दशा, भविष्यवाणियाँ, कुंडली मिलान), दैनिक पंचांग, चौघड़िया व मुहूर्त, व्रत-त्योहार कैलेंडर, उपाय व मार्गदर्शन सुविधाएँ, तथा वेद-पुराण-गीता-रामायण आदि का दिव्य पुस्तकालय (ऑडियो सहित) प्रदान करता है। कुछ सुविधाओं हेतु सशुल्क सदस्यता आवश्यक है।',
    },
  },
  {
    h: { en: '3. Important disclaimer — guidance, not advice', hi: '3. महत्वपूर्ण अस्वीकरण — मार्गदर्शन, सलाह नहीं' },
    b: {
      en: 'Astrology is a matter of tradition and personal belief. Everything in this app — predictions, readings, muhurats, remedies, match-making scores and answers to your questions — is offered for spiritual, cultural and informational purposes only. It is NOT medical, legal, financial, psychological or professional advice, and must never replace consulting a qualified professional. We make no guarantee that any predicted outcome will occur. Decisions you take based on the app\'s content are entirely your own responsibility. If you are in distress, please seek qualified help.',
      hi: 'ज्योतिष परंपरा व व्यक्तिगत आस्था का विषय है। इस ऐप की हर सामग्री — भविष्यवाणियाँ, रीडिंग, मुहूर्त, उपाय, कुंडली मिलान के अंक व आपके प्रश्नों के उत्तर — केवल आध्यात्मिक, सांस्कृतिक व सूचनात्मक उद्देश्य से है। यह चिकित्सीय, कानूनी, वित्तीय, मानसिक-स्वास्थ्य या किसी भी व्यावसायिक सलाह का विकल्प नहीं है, और योग्य विशेषज्ञ से परामर्श की जगह कभी न ले। किसी भी भविष्यवाणी के फलित होने की हम कोई गारंटी नहीं देते। ऐप की सामग्री के आधार पर लिए गए निर्णयों की जिम्मेदारी पूर्णतः आपकी है। कठिनाई में हों तो कृपया योग्य सहायता लें।',
    },
  },
  {
    h: { en: '4. Accuracy of calculations', hi: '4. गणनाओं की शुद्धता' },
    b: {
      en: 'Panchang, choghadiya, festival dates and planetary positions are computed from astronomical data with great care and are cross-checked against established panchang references. Even so, traditions differ: dates and timings can legitimately vary by region, sampradaya and the panchang followed (for example Purnimanta vs Amanta months). For important ceremonies, please confirm timings with your family purohit or local panchang. The accuracy of personalised results also depends on the birth details you enter.',
      hi: 'पंचांग, चौघड़िया, त्योहार-तिथियाँ व ग्रह-स्थिति खगोलीय डेटा से पूरी सावधानी से गणना होती हैं और प्रतिष्ठित पंचांग संदर्भों से मिलान की जाती हैं। फिर भी परंपराएँ भिन्न हैं: क्षेत्र, संप्रदाय व अनुसरण किए गए पंचांग (जैसे पूर्णिमान्त बनाम अमान्त मास) के अनुसार तिथियाँ/समय वैध रूप से भिन्न हो सकते हैं। महत्वपूर्ण संस्कारों हेतु कृपया अपने पुरोहित या स्थानीय पंचांग से समय की पुष्टि करें। व्यक्तिगत परिणामों की शुद्धता आपके भरे जन्म-विवरण पर भी निर्भर है।',
    },
  },
  {
    h: { en: '5. Your account', hi: '5. आपका खाता' },
    b: {
      en: 'You agree to provide accurate information and to keep your OTPs and device secure. For your protection the app enforces single-device login: signing in on a new device signs the previous one out. You are responsible for activity on your account. We may suspend accounts that violate these terms or abuse the service.',
      hi: 'आप सही जानकारी देने तथा अपने OTP व डिवाइस को सुरक्षित रखने पर सहमत हैं। आपकी सुरक्षा हेतु ऐप में सिंगल-डिवाइस लॉगिन लागू है: नए डिवाइस पर साइन-इन करते ही पिछला लॉगआउट हो जाता है। आपके खाते की गतिविधि की जिम्मेदारी आपकी है। शर्तों का उल्लंघन या सेवा के दुरुपयोग पर हम खाता निलंबित कर सकते हैं।',
    },
  },
  {
    h: { en: '6. Subscriptions, payments & refunds', hi: '6. सदस्यता, भुगतान व रिफंड' },
    b: {
      en: 'Premium features are available through paid plans shown in the app. Prices include applicable taxes unless stated otherwise. Payments are processed by third-party payment providers; we do not store your card or UPI credentials. Subscriptions run for the period purchased. If a paid feature fails to work and we cannot fix it within a reasonable time, contact support within 7 days of the charge for a review of your refund request — refunds, where approved, are made to the original payment method. Where the purchase is made through an app store, that store\'s refund policy also applies.',
      hi: 'प्रीमियम सुविधाएँ ऐप में दिखाए गए सशुल्क प्लान से मिलती हैं। जब तक अन्यथा न कहा जाए, कीमतों में लागू कर सम्मिलित हैं। भुगतान थर्ड-पार्टी भुगतान-प्रदाता संसाधित करते हैं; हम आपका कार्ड/UPI विवरण संग्रहीत नहीं करते। सदस्यता खरीदी गई अवधि तक चलती है। कोई सशुल्क सुविधा काम न करे और हम उचित समय में ठीक न कर पाएँ, तो शुल्क के 7 दिनों के भीतर सपोर्ट से संपर्क करें — स्वीकृत रिफंड मूल भुगतान-माध्यम में किए जाते हैं। ऐप-स्टोर से की गई खरीद पर उस स्टोर की रिफंड नीति भी लागू होगी।',
    },
  },
  {
    h: { en: '7. Content & intellectual property', hi: '7. सामग्री व बौद्धिक संपदा' },
    b: {
      en: 'The scriptures in the Divine Library (Vedas, Puranas, Gita, Ramayana and others) are the timeless heritage of humanity, reproduced from public-domain editions. The app\'s design, code, translations, retellings, explanations, audio arrangements and compilation are the property of Shree Yantra and are licensed to you for personal, non-commercial use within the app. You may not copy, scrape, extract in bulk, resell or republish the app\'s content, or use automated tools against the service.',
      hi: 'दिव्य पुस्तकालय के ग्रंथ (वेद, पुराण, गीता, रामायण आदि) मानवता की शाश्वत धरोहर हैं, जो सार्वजनिक-डोमेन संस्करणों से लिए गए हैं। ऐप का डिज़ाइन, कोड, अनुवाद, कथाएँ, व्याख्याएँ, ऑडियो-संयोजन व संकलन श्री यंत्र की संपत्ति हैं और आपको केवल ऐप के भीतर व्यक्तिगत, गैर-व्यावसायिक उपयोग हेतु लाइसेंस पर उपलब्ध हैं। ऐप की सामग्री की नकल, स्क्रैपिंग, थोक निष्कर्षण, पुनर्विक्रय या पुनर्प्रकाशन, अथवा सेवा पर स्वचालित टूल का उपयोग वर्जित है।',
    },
  },
  {
    h: { en: '8. Acceptable use', hi: '8. उचित उपयोग' },
    b: {
      en: 'You agree not to misuse the service — including attempting to breach security, accessing another person\'s account or data, reverse-engineering the app, sending abusive content through any feature, or using the app for unlawful purposes.',
      hi: 'आप सेवा का दुरुपयोग न करने पर सहमत हैं — जिसमें सुरक्षा तोड़ने का प्रयास, किसी अन्य के खाते/डेटा तक पहुँच, ऐप की रिवर्स-इंजीनियरिंग, किसी सुविधा से आपत्तिजनक सामग्री भेजना, या ऐप का गैर-कानूनी उपयोग शामिल है।',
    },
  },
  {
    h: { en: '9. Limitation of liability', hi: '9. दायित्व की सीमा' },
    b: {
      en: 'The app and its content are provided "as is" and "as available". To the maximum extent permitted by law, Shree Yantra is not liable for indirect or consequential losses, or for decisions taken in reliance on astrological content (see Section 3). Our total liability for any claim is limited to the amount you paid us in the 12 months before the claim. Nothing in these terms limits rights that cannot be limited under applicable consumer law.',
      hi: 'ऐप व इसकी सामग्री "जैसी है" व "जैसी उपलब्ध है" आधार पर दी जाती है। कानून द्वारा अनुमत अधिकतम सीमा तक, श्री यंत्र अप्रत्यक्ष या परिणामी हानियों, अथवा ज्योतिषीय सामग्री पर भरोसा कर लिए गए निर्णयों (धारा 3 देखें) हेतु उत्तरदायी नहीं है। किसी भी दावे हेतु हमारा कुल दायित्व, दावे से पूर्व 12 महीनों में आपके द्वारा हमें किए भुगतान तक सीमित है। ये शर्तें उपभोक्ता कानून के अंतर्गत असीमित-योग्य अधिकारों को सीमित नहीं करतीं।',
    },
  },
  {
    h: { en: '10. Changes, termination & governing law', hi: '10. बदलाव, समाप्ति व लागू कानून' },
    b: {
      en: `We may update the app and these terms; material changes will be notified in the app and continued use after the effective date means acceptance. You may stop using the service at any time and may request account deletion as described in the Privacy Policy. These terms are governed by the laws of India, and courts at Jodhpur, Rajasthan shall have exclusive jurisdiction. Questions: ${CONTACT_EMAIL}.`,
      hi: `हम ऐप व इन शर्तों को अपडेट कर सकते हैं; महत्वपूर्ण बदलावों की सूचना ऐप में दी जाएगी और प्रभावी तिथि के बाद उपयोग जारी रखना स्वीकृति मानी जाएगी। आप कभी भी सेवा का उपयोग बंद कर सकते हैं और गोपनीयता नीति में बताए अनुसार खाता हटाने का अनुरोध कर सकते हैं। इन शर्तों पर भारत का कानून लागू है और जोधपुर, राजस्थान के न्यायालयों को ही क्षेत्राधिकार होगा। प्रश्न: ${CONTACT_EMAIL}।`,
    },
  },
];


export const LEGAL_UPDATED = UPDATED
export const LEGAL_CONTACT = CONTACT_EMAIL
export const LEGAL_PRIVACY = PRIVACY
export const LEGAL_TERMS = TERMS
