// Builds a gold-themed Shubh Muhurat report HTML for expo-print → PDF.
import { MuhuratResult, MuhuratItem } from './api';

const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const esc = (s: any) => String(s ?? '').replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' } as any)[c]);
const dmyLabel = (dmy: string) => { const [d, m, y] = String(dmy).split('/').map(Number); return `${d} ${MON[(m - 1) % 12]} ${y}`; };
const stars = (s: number) => '★'.repeat(Math.max(1, Math.min(5, Math.round(s / 20))));

function itemBlock(it: MuhuratItem, best: boolean): string {
  const time = it.time.abhijit ? `${esc(it.time.abhijit.start)} – ${esc(it.time.abhijit.end)}` : '—';
  const rows = [
    ['Tithi', it.tithi.name], ['Nakshatra', it.nakshatra.name], ['Yoga', it.yoga?.name || '—'],
    ['Karana', it.karana?.name || '—'], ['Moon Sign', it.moonSign?.en || '—'],
    ['Chandrabal', it.chandra?.label?.en || '—'], ['Tara Bal', it.tara ? `${it.tara.en}` : '—'],
    ['Choghadiya', it.flags.choghadiya || '—'], ['Rahu Kaal', 'Removed'], ['Bhadra', 'No'], ['Panchak', 'No'],
  ].map(([k, v]) => `<td class="c"><span class="k">${esc(k)}</span><span class="v">${esc(v)}</span></td>`).join('');
  const why = it.breakdown.filter((b) => b.ok).map((b) => `<li>${esc(b.en)} <b>+${b.pts}</b></li>`).join('');
  return `<div class="card ${best ? 'best' : ''}">
    <div class="ch">
      <div><div class="date">${dmyLabel(it.dmy)}</div><div class="wd">${esc(it.weekday)}${it.time.abhijit ? ` · ${time}` : ''}</div></div>
      <div class="score"><div class="sn">${it.score}</div><div class="sm">/100 ${stars(it.score)}</div><div class="rt">${esc(it.rating.en)}</div></div>
    </div>
    <table class="grid"><tr>${rows}</tr></table>
    <div class="why"><b>Why this Muhurat?</b><ul>${why}</ul></div>
  </div>`;
}

export function buildMuhuratHtml(result: MuhuratResult, place: string): string {
  const catName = result.category.name.en;
  const best = result.best;
  const rest = result.items.filter((i) => !best || i.dmy !== best.dmy).slice(0, 8);
  return `<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
  <style>
    *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#2a1c06;margin:0;padding:26px;background:#fffdf6}
    h1{font-size:22px;margin:0 0 2px;color:#7a4e08} .sub{color:#8a6a2a;font-size:12px;margin-bottom:18px}
    .card{border:1px solid #e3cf9a;border-radius:14px;padding:14px;margin-bottom:14px;background:#fff}
    .card.best{border:2px solid #c99422;background:linear-gradient(135deg,#fff7e0,#fdeec0)}
    .ch{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px}
    .date{font-size:19px;font-weight:800;color:#3a2606} .wd{font-size:12px;color:#7a5a20;margin-top:2px}
    .score{text-align:right} .sn{font-size:26px;font-weight:800;color:#9a6b12;line-height:1} .sm{font-size:11px;color:#b58a2a} .rt{font-size:11px;font-weight:700;color:#3a2606}
    .grid{width:100%;border-collapse:collapse} .grid td{border:1px solid #eaddb8;padding:5px 7px;width:9%;vertical-align:top}
    .k{display:block;font-size:8.5px;color:#9a8552;text-transform:uppercase} .v{display:block;font-size:11px;font-weight:600;margin-top:1px}
    .why{margin-top:10px;font-size:11px} .why ul{margin:4px 0 0;padding-left:16px} .why li{margin:1px 0}
    .badge{margin-top:6px;font-size:10.5px;color:#6a5426} .tag{display:inline-block;border:1px solid #d9c284;border-radius:20px;padding:2px 8px;margin:2px 3px 0 0;font-size:9.5px;color:#7a5a20}
    .foot{margin-top:14px;font-size:10px;color:#8a744a;line-height:1.5}
  </style></head><body>
    <h1>🏆 Shubh Muhurat — ${esc(catName)}</h1>
    <div class="sub">📍 ${esc(place || '—')} · Calculated with Lahiri ayanamsa & classical Muhurta rules</div>
    <div class="badge"><b>Calculated using:</b>
      ${['Panchang', 'Astronomy Engine', 'Lahiri Ayanamsa', 'Chandrabal', 'Tara Bal', 'Choghadiya', 'Rahu Kaal', 'Bhadra', 'Panchak'].map((t) => `<span class="tag">✔ ${t}</span>`).join('')}
    </div>
    <div style="height:14px"></div>
    ${best ? `<div style="font-weight:800;color:#7a4e08;margin-bottom:6px">🏆 Best Muhurat</div>${itemBlock(best, true)}` : ''}
    ${rest.length ? `<div style="font-weight:800;color:#7a4e08;margin:14px 0 6px">Other Recommended Muhurats</div>${rest.map((it) => itemBlock(it, false)).join('')}` : ''}
    <div class="foot">This report follows the app’s classical scoring model. Different jyotish traditions may prioritise factors differently. For very important events, also confirm the lagna with a learned pandit.<br/>Generated by Shree Yantra.</div>
  </body></html>`;
}
